// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1CICj6zHqdODF_haNcTce9smWibwz7Q',
    appId: '1:175737024308:web:5598aa9acd5e92bcad3f61',
    messagingSenderId: '175737024308',
    projectId: 'supermeals-f04aa',
    authDomain: 'supermeals-f04aa.firebaseapp.com',
    storageBucket: 'supermeals-f04aa.appspot.com',
    measurementId: 'G-L55L8RH8DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGrQOJJxa5Ki9YaqlDp9ujgNu8DPOUXNI',
    appId: '1:175737024308:android:14085ee65c1747fead3f61',
    messagingSenderId: '175737024308',
    projectId: 'supermeals-f04aa',
    storageBucket: 'supermeals-f04aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5lVekx3nwTerQGOYQLYDdIzMTgzPP5Q',
    appId: '1:175737024308:ios:8405d0d054ce29f1ad3f61',
    messagingSenderId: '175737024308',
    projectId: 'supermeals-f04aa',
    storageBucket: 'supermeals-f04aa.appspot.com',
    iosBundleId: 'com.example.superMeals',
  );
}
